// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#ifndef UI_SCRCONFIG_H
#define UI_SCRCONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrconfig
extern void ui_scrconfig_screen_init(void);
extern void ui_scrconfig_screen_destroy(void);
extern lv_obj_t * ui_scrconfig;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_hdrleft;
extern lv_obj_t * ui_dot;
extern lv_obj_t * ui_lbltitle;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_uikbdisplay;
extern lv_obj_t * ui_rowscont;
extern lv_obj_t * ui_row1;
extern lv_obj_t * ui_lblname1;
extern lv_obj_t * ui_lblvalue1;
extern lv_obj_t * ui_row2;
extern lv_obj_t * ui_lblname2;
extern lv_obj_t * ui_lblvalue2;
extern lv_obj_t * ui_row3;
extern lv_obj_t * ui_lblname3;
extern lv_obj_t * ui_lblvalue3;
extern lv_obj_t * ui_row4;
extern lv_obj_t * ui_lblname4;
extern lv_obj_t * ui_lblvalue4;
extern void ui_event_btnstart(lv_event_t * e);
extern lv_obj_t * ui_btnstart;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_uicfgpopup;
extern lv_obj_t * ui_uicfgpopuppanel;
extern lv_obj_t * ui_uicfgpopuphdr;
extern lv_obj_t * ui_uicfgpopupdot;
extern lv_obj_t * ui_uicfgpopuptitle;
extern lv_obj_t * ui_uicfgpopuplbl;
extern void ui_event_uicfgpopupbtnok(lv_event_t * e);
extern lv_obj_t * ui_uicfgpopupbtnok;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_lbltitle;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

