// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#include "../ui.h"

lv_obj_t * ui_scrsweep = NULL;
lv_obj_t * ui_swheader = NULL;
lv_obj_t * ui_swhdrleft = NULL;
lv_obj_t * ui_swindicator = NULL;
lv_obj_t * ui_swlblstatus = NULL;
lv_obj_t * ui_swhdrright = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_swchart = NULL;
lv_obj_t * ui_swchart_Xaxis = NULL;
lv_obj_t * ui_swchart_Yaxis1 = NULL;
lv_obj_t * ui_swchart_Yaxis2 = NULL;
lv_obj_t * ui_swfooter = NULL;
lv_obj_t * ui_swbtnpausar = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_swbtnconfig = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_swbtnreinicio = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_swbtnpausar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_btn_pausar(e);
    }
}

void ui_event_swbtnconfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_btn_config(e);
    }
}

void ui_event_swbtnreinicio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_btn_reiniciar(e);
    }
}

// build funtions

void ui_scrsweep_screen_init(void)
{
    ui_scrsweep = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrsweep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_scrsweep, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_scrsweep, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_scrsweep, lv_color_hex(0x081422), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrsweep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_scrsweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_scrsweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_scrsweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_scrsweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_scrsweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_scrsweep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrsweep, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swheader = lv_obj_create(ui_scrsweep);
    lv_obj_set_width(ui_swheader, 320);
    lv_obj_set_height(ui_swheader, 28);
    lv_obj_set_align(ui_swheader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_swheader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_swheader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_swheader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swheader, lv_color_hex(0x1D3A5F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_swheader, lv_color_hex(0x0E2440), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_swheader, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_swheader, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_swheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swheader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_swheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_swheader, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_swheader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_swheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_swheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swhdrleft = lv_obj_create(ui_swheader);
    lv_obj_set_height(ui_swhdrleft, 28);
    lv_obj_set_flex_grow(ui_swhdrleft, 1);
    lv_obj_set_align(ui_swhdrleft, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_swhdrleft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_swhdrleft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_swhdrleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swhdrleft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_swhdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_swhdrleft, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swindicator = lv_obj_create(ui_swhdrleft);
    lv_obj_set_width(ui_swindicator, 8);
    lv_obj_set_height(ui_swindicator, 8);
    lv_obj_set_align(ui_swindicator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_swindicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swindicator, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swindicator, lv_color_hex(0x3EE08A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swindicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_swindicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swlblstatus = lv_label_create(ui_swhdrleft);
    lv_obj_set_width(ui_swlblstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_swlblstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_swlblstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_swlblstatus, "BARRIDO");
    lv_obj_set_style_text_color(ui_swlblstatus, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swlblstatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_swlblstatus, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swhdrright = lv_obj_create(ui_swheader);
    lv_obj_set_width(ui_swhdrright, 100);
    lv_obj_set_height(ui_swhdrright, 28);
    lv_obj_set_align(ui_swhdrright, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_swhdrright, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_swhdrright, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_swhdrright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swhdrright, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_swhdrright, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_swhdrright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_swhdrright, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_scrsweep);
    lv_obj_set_width(ui_Panel1, 320);
    lv_obj_set_height(ui_Panel1, 172);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x081420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swchart = lv_chart_create(ui_Panel1);
    lv_obj_set_width(ui_swchart, 285);
    lv_obj_set_height(ui_swchart, 140);
    lv_obj_set_x(ui_swchart, -12);
    lv_obj_set_y(ui_swchart, 5);
    lv_obj_set_align(ui_swchart, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_swchart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_swchart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_swchart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_swchart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_swchart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_swchart, 200);
    lv_chart_set_axis_range(ui_swchart, LV_CHART_AXIS_PRIMARY_Y, -40, 3);
    lv_chart_set_axis_range(ui_swchart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_swchart, 9, 5);
    lv_obj_set_style_radius(ui_swchart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swchart, lv_color_hex(0x081422), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swchart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swchart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_swchart, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_swchart, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_swchart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swchart_Xaxis = lv_scale_create(ui_swchart);
    lv_scale_set_mode(ui_swchart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_swchart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_swchart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_swchart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_swchart,
                                                                    LV_PART_MAIN) + lv_obj_get_style_border_width(ui_swchart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_swchart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_swchart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_swchart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_swchart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_swchart_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_swchart_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_swchart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_swchart_Xaxis, 2 >= 1 ? 2 : 1);
    ui_swchart_Yaxis1 = lv_scale_create(ui_swchart);
    lv_scale_set_mode(ui_swchart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_swchart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_swchart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_swchart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_swchart,
                                                                    LV_PART_MAIN) - lv_obj_get_style_border_width(ui_swchart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_swchart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_swchart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_swchart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_swchart_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_swchart_Yaxis1, 1, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_swchart_Yaxis1,  -40, 3);
    lv_scale_set_total_tick_count(ui_swchart_Yaxis1, (9 > 0 ? 9 - 1 : 0) * 3 + 1);
    lv_scale_set_major_tick_every(ui_swchart_Yaxis1, 3 >= 1 ? 3 : 1);
    ui_swchart_Yaxis2 = lv_scale_create(ui_swchart);
    lv_scale_set_mode(ui_swchart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_swchart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_swchart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_swchart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_swchart,
                                                                    LV_PART_MAIN) + lv_obj_get_style_border_width(ui_swchart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_swchart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_swchart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_swchart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_swchart_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_swchart_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_swchart_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_swchart_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_swchart_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_swchart_Yaxis2, false);

    lv_obj_set_style_line_width(ui_swchart, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_swchart, 0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_swchart_Xaxis, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swchart_Xaxis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_swchart_Yaxis1, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swchart_Yaxis1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_swchart_Yaxis2, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swchart_Yaxis2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_swchart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_swchart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_swfooter = lv_obj_create(ui_scrsweep);
    lv_obj_set_width(ui_swfooter, 320);
    lv_obj_set_height(ui_swfooter, 40);
    lv_obj_set_align(ui_swfooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_swfooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_swfooter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_swfooter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swfooter, lv_color_hex(0x0C2138), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swfooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_swfooter, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_swfooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swfooter, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_swfooter, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_swfooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swbtnpausar = lv_button_create(ui_swfooter);
    lv_obj_set_height(ui_swbtnpausar, 40);
    lv_obj_set_flex_grow(ui_swbtnpausar, 1);
    lv_obj_set_x(ui_swbtnpausar, 16);
    lv_obj_set_y(ui_swbtnpausar, -18);
    lv_obj_set_align(ui_swbtnpausar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_swbtnpausar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_swbtnpausar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swbtnpausar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swbtnpausar, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swbtnpausar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_swbtnpausar, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_swbtnpausar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swbtnpausar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_swbtnpausar, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_swbtnpausar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_swbtnpausar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swbtnpausar, lv_color_hex(0x1A8FAB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_swbtnpausar, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_swbtnpausar);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "PAUSAR");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x062033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swbtnconfig = lv_button_create(ui_swfooter);
    lv_obj_set_height(ui_swbtnconfig, 40);
    lv_obj_set_flex_grow(ui_swbtnconfig, 1);
    lv_obj_set_x(ui_swbtnconfig, 16);
    lv_obj_set_y(ui_swbtnconfig, -18);
    lv_obj_set_align(ui_swbtnconfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_swbtnconfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_swbtnconfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swbtnconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swbtnconfig, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swbtnconfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_swbtnconfig, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_swbtnconfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_swbtnconfig, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_swbtnconfig, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_swbtnconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_swbtnconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swbtnconfig, lv_color_hex(0x1A8FAB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_swbtnconfig, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label2 = lv_label_create(ui_swbtnconfig);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "< CONFIG");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x062033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swbtnreinicio = lv_button_create(ui_swfooter);
    lv_obj_set_height(ui_swbtnreinicio, 40);
    lv_obj_set_flex_grow(ui_swbtnreinicio, 1);
    lv_obj_set_x(ui_swbtnreinicio, 16);
    lv_obj_set_y(ui_swbtnreinicio, -18);
    lv_obj_set_align(ui_swbtnreinicio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_swbtnreinicio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_swbtnreinicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_swbtnreinicio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swbtnreinicio, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swbtnreinicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_swbtnreinicio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_swbtnreinicio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_swbtnreinicio, lv_color_hex(0x1A8FAB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_swbtnreinicio, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_swbtnreinicio);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "REINICIAR");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x062033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_swbtnpausar, ui_event_swbtnpausar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swbtnconfig, ui_event_swbtnconfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swbtnreinicio, ui_event_swbtnreinicio, LV_EVENT_ALL, NULL);

}

void ui_scrsweep_screen_destroy(void)
{
    if(ui_scrsweep) lv_obj_del(ui_scrsweep);

    // NULL screen variables
    ui_scrsweep = NULL;
    ui_swheader = NULL;
    ui_swhdrleft = NULL;
    ui_swindicator = NULL;
    ui_swlblstatus = NULL;
    ui_swhdrright = NULL;
    ui_Panel1 = NULL;
    ui_swchart = NULL;
    ui_swfooter = NULL;
    ui_swbtnpausar = NULL;
    ui_Label1 = NULL;
    ui_swbtnconfig = NULL;
    ui_Label2 = NULL;
    ui_swbtnreinicio = NULL;
    ui_Label3 = NULL;

}
