// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#ifndef UI_SCRSWEEP_H
#define UI_SCRSWEEP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrsweep
extern void ui_scrsweep_screen_init(void);
extern void ui_scrsweep_screen_destroy(void);
extern lv_obj_t * ui_scrsweep;
extern lv_obj_t * ui_swheader;
extern lv_obj_t * ui_swhdrleft;
extern lv_obj_t * ui_swindicator;
extern lv_obj_t * ui_swlblstatus;
extern lv_obj_t * ui_swhdrright;
extern lv_obj_t * ui_swchart;
extern lv_obj_t * ui_swchart_Xaxis;
extern lv_obj_t * ui_swchart_Yaxis1;
extern lv_obj_t * ui_swchart_Yaxis2;
extern lv_obj_t * ui_swfooter;
extern void ui_event_swbtnpausar(lv_event_t * e);
extern lv_obj_t * ui_swbtnpausar;
extern lv_obj_t * ui_Label1;
extern void ui_event_swbtnconfig(lv_event_t * e);
extern lv_obj_t * ui_swbtnconfig;
extern lv_obj_t * ui_Label2;
extern void ui_event_swbtnreinicio(lv_event_t * e);
extern lv_obj_t * ui_swbtnreinicio;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

