// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#include "../ui.h"

lv_obj_t * uic_lbltitle;
lv_obj_t * ui_scrconfig = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_hdrleft = NULL;
lv_obj_t * ui_dot = NULL;
lv_obj_t * ui_lbltitle = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_uikbdisplay = NULL;
lv_obj_t * ui_rowscont = NULL;
lv_obj_t * ui_row1 = NULL;
lv_obj_t * ui_lblname1 = NULL;
lv_obj_t * ui_lblvalue1 = NULL;
lv_obj_t * ui_row2 = NULL;
lv_obj_t * ui_lblname2 = NULL;
lv_obj_t * ui_lblvalue2 = NULL;
lv_obj_t * ui_row3 = NULL;
lv_obj_t * ui_lblname3 = NULL;
lv_obj_t * ui_lblvalue3 = NULL;
lv_obj_t * ui_row4 = NULL;
lv_obj_t * ui_lblname4 = NULL;
lv_obj_t * ui_lblvalue4 = NULL;
lv_obj_t * ui_btnstart = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_uicfgpopup = NULL;
lv_obj_t * ui_uicfgpopuppanel = NULL;
lv_obj_t * ui_uicfgpopuphdr = NULL;
lv_obj_t * ui_uicfgpopupdot = NULL;
lv_obj_t * ui_uicfgpopuptitle = NULL;
lv_obj_t * ui_uicfgpopuplbl = NULL;
lv_obj_t * ui_uicfgpopupbtnok = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_btnstart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_btn_start(e);
    }
}

void ui_event_uicfgpopupbtnok(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_cfg_popup_ok(e);
    }
}

// build funtions

void ui_scrconfig_screen_init(void)
{
    ui_scrconfig = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrconfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_scrconfig, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_scrconfig, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_scrconfig, lv_color_hex(0x0B1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrconfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_scrconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_scrconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_scrconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_scrconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_scrconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_scrconfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrconfig, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header = lv_obj_create(ui_scrconfig);
    lv_obj_set_width(ui_header, 320);
    lv_obj_set_height(ui_header, 28);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_header, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x1D3A5F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_header, lv_color_hex(0x0E2440), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_header, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_header, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_header, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hdrleft = lv_obj_create(ui_header);
    lv_obj_set_width(ui_hdrleft, 220);
    lv_obj_set_height(ui_hdrleft, 28);
    lv_obj_set_align(ui_hdrleft, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hdrleft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hdrleft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_hdrleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hdrleft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_hdrleft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_hdrleft, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot = lv_obj_create(ui_hdrleft);
    lv_obj_set_width(ui_dot, 9);
    lv_obj_set_height(ui_dot, 9);
    lv_obj_set_align(ui_dot, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_dot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltitle = lv_label_create(ui_hdrleft);
    lv_obj_set_width(ui_lbltitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltitle, 84);
    lv_obj_set_y(ui_lbltitle, -1);
    lv_obj_set_align(ui_lbltitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltitle, "Analizador Frec.");
    lv_obj_set_style_text_color(ui_lbltitle, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbltitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbltitle, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_header);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "CONFIGURAR >");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x9BB6D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uikbdisplay = lv_label_create(ui_scrconfig);
    lv_obj_set_width(ui_uikbdisplay, 320);
    lv_obj_set_height(ui_uikbdisplay, 28);
    lv_obj_set_align(ui_uikbdisplay, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_uikbdisplay, "");
    lv_obj_add_flag(ui_uikbdisplay, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_uikbdisplay, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uikbdisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uikbdisplay, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uikbdisplay, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uikbdisplay, lv_color_hex(0x0F2C40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uikbdisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uikbdisplay, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uikbdisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uikbdisplay, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uikbdisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uikbdisplay, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uikbdisplay, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uikbdisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowscont = lv_obj_create(ui_scrconfig);
    lv_obj_set_width(ui_rowscont, 320);
    lv_obj_set_height(ui_rowscont, 160);
    lv_obj_set_x(ui_rowscont, 3);
    lv_obj_set_y(ui_rowscont, 32);
    lv_obj_set_align(ui_rowscont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rowscont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rowscont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_rowscont, LV_DIR_VER);
    lv_obj_set_style_radius(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rowscont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_rowscont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row1 = lv_obj_create(ui_rowscont);
    lv_obj_set_width(ui_row1, 320);
    lv_obj_set_height(ui_row1, 32);
    lv_obj_set_align(ui_row1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_row1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_row1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_row1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_row1, lv_color_hex(0x0B1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_row1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_row1, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_row1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_row1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_row1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_row1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_row1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_row1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_row1, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_row1, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblname1 = lv_label_create(ui_row1);
    lv_obj_set_width(ui_lblname1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblname1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblname1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblname1, "Frecuencia inicial");
    lv_obj_set_style_text_color(ui_lblname1, lv_color_hex(0xA9C2DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblname1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblname1, &ui_font_RobotoMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvalue1 = lv_label_create(ui_row1);
    lv_obj_set_width(ui_lblvalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvalue1, -5);
    lv_obj_set_y(ui_lblvalue1, 0);
    lv_obj_set_align(ui_lblvalue1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblvalue1, "10 Hz");
    lv_obj_add_flag(ui_lblvalue1, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblvalue1, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblvalue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblvalue1, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row2 = lv_obj_create(ui_rowscont);
    lv_obj_set_width(ui_row2, 320);
    lv_obj_set_height(ui_row2, 32);
    lv_obj_set_align(ui_row2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_row2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_row2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_row2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_row2, lv_color_hex(0x0B1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_row2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_row2, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_row2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_row2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_row2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_row2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_row2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_row2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_row2, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_row2, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblname2 = lv_label_create(ui_row2);
    lv_obj_set_width(ui_lblname2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblname2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblname2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblname2, "Frecuencia final");
    lv_obj_set_style_text_color(ui_lblname2, lv_color_hex(0xA9C2DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblname2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblname2, &ui_font_RobotoMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvalue2 = lv_label_create(ui_row2);
    lv_obj_set_width(ui_lblvalue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvalue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvalue2, -5);
    lv_obj_set_y(ui_lblvalue2, 0);
    lv_obj_set_align(ui_lblvalue2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblvalue2, "100 kHz");
    lv_obj_add_flag(ui_lblvalue2, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblvalue2, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblvalue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblvalue2, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row3 = lv_obj_create(ui_rowscont);
    lv_obj_set_width(ui_row3, 320);
    lv_obj_set_height(ui_row3, 32);
    lv_obj_set_align(ui_row3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_row3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_row3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_row3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_row3, lv_color_hex(0x0B1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_row3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_row3, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_row3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_row3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_row3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_row3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_row3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_row3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_row3, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_row3, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblname3 = lv_label_create(ui_row3);
    lv_obj_set_width(ui_lblname3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblname3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblname3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblname3, "Cant. de puntos");
    lv_obj_set_style_text_color(ui_lblname3, lv_color_hex(0xA9C2DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblname3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblname3, &ui_font_RobotoMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvalue3 = lv_label_create(ui_row3);
    lv_obj_set_width(ui_lblvalue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvalue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvalue3, -5);
    lv_obj_set_y(ui_lblvalue3, 0);
    lv_obj_set_align(ui_lblvalue3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblvalue3, "200");
    lv_obj_add_flag(ui_lblvalue3, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblvalue3, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblvalue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblvalue3, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row4 = lv_obj_create(ui_rowscont);
    lv_obj_set_width(ui_row4, 320);
    lv_obj_set_height(ui_row4, 32);
    lv_obj_set_align(ui_row4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_row4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_row4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_row4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_row4, lv_color_hex(0x0B1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_row4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_row4, lv_color_hex(0x1C3A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_row4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_row4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_row4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_row4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_row4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_row4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_row4, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_row4, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblname4 = lv_label_create(ui_row4);
    lv_obj_set_width(ui_lblname4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblname4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblname4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblname4, "Tiempo de asentamiento");
    lv_obj_set_style_text_color(ui_lblname4, lv_color_hex(0xA9C2DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblname4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblname4, &ui_font_RobotoMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvalue4 = lv_label_create(ui_row4);
    lv_obj_set_width(ui_lblvalue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvalue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvalue4, -5);
    lv_obj_set_y(ui_lblvalue4, 0);
    lv_obj_set_align(ui_lblvalue4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblvalue4, "30 ms");
    lv_obj_add_flag(ui_lblvalue4, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_set_style_text_color(ui_lblvalue4, lv_color_hex(0xEAF2FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblvalue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblvalue4, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnstart = lv_button_create(ui_scrconfig);
    lv_obj_set_width(ui_btnstart, 320);
    lv_obj_set_height(ui_btnstart, 52);
    lv_obj_set_align(ui_btnstart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnstart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnstart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnstart, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnstart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_btnstart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnstart, lv_color_hex(0x1A8FAB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnstart, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label7 = lv_label_create(ui_btnstart);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "INICIAR BARRIDO");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x062033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_RobotoMono18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_scrconfig);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_USER_1);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 212);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 14);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags

    ui_uicfgpopup = lv_obj_create(ui_scrconfig);
    lv_obj_set_width(ui_uicfgpopup, 320);
    lv_obj_set_height(ui_uicfgpopup, 240);
    lv_obj_set_align(ui_uicfgpopup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uicfgpopup, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_remove_flag(ui_uicfgpopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uicfgpopup, lv_color_hex(0x040A14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uicfgpopup, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uicfgpopup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uicfgpopuppanel = lv_obj_create(ui_uicfgpopup);
    lv_obj_set_width(ui_uicfgpopuppanel, 260);
    lv_obj_set_height(ui_uicfgpopuppanel, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_uicfgpopuppanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uicfgpopuppanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uicfgpopuppanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_uicfgpopuppanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uicfgpopuppanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uicfgpopuppanel, lv_color_hex(0x0E2440), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uicfgpopuppanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uicfgpopuppanel, lv_color_hex(0xE05A2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uicfgpopuppanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uicfgpopuppanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uicfgpopuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uicfgpopuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uicfgpopuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uicfgpopuppanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_uicfgpopuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uicfgpopuppanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uicfgpopuphdr = lv_obj_create(ui_uicfgpopuppanel);
    lv_obj_set_width(ui_uicfgpopuphdr, 260);
    lv_obj_set_height(ui_uicfgpopuphdr, 30);
    lv_obj_set_align(ui_uicfgpopuphdr, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uicfgpopuphdr, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uicfgpopuphdr, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_uicfgpopuphdr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uicfgpopuphdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uicfgpopuphdr, lv_color_hex(0x1A1000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uicfgpopuphdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uicfgpopuphdr, lv_color_hex(0xE05A2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uicfgpopuphdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uicfgpopuphdr, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uicfgpopuphdr, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uicfgpopuphdr, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uicfgpopuphdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uicfgpopuphdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uicfgpopupdot = lv_obj_create(ui_uicfgpopuphdr);
    lv_obj_set_width(ui_uicfgpopupdot, 8);
    lv_obj_set_height(ui_uicfgpopupdot, 8);
    lv_obj_set_align(ui_uicfgpopupdot, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_uicfgpopupdot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uicfgpopupdot, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uicfgpopupdot, lv_color_hex(0xE05A2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uicfgpopupdot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_uicfgpopupdot, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uicfgpopuptitle = lv_label_create(ui_uicfgpopuphdr);
    lv_obj_set_width(ui_uicfgpopuptitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uicfgpopuptitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uicfgpopuptitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uicfgpopuptitle, "CONFIGURACIÓN INVALIDA");
    lv_obj_set_style_text_color(ui_uicfgpopuptitle, lv_color_hex(0xF0A070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uicfgpopuptitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uicfgpopuptitle, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uicfgpopuplbl = lv_label_create(ui_uicfgpopuppanel);
    lv_obj_set_width(ui_uicfgpopuplbl, 236);
    lv_obj_set_height(ui_uicfgpopuplbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uicfgpopuplbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uicfgpopuplbl, "");
    lv_obj_remove_flag(ui_uicfgpopuplbl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_uicfgpopuplbl, lv_color_hex(0xC8D8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uicfgpopuplbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uicfgpopuplbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_uicfgpopuplbl, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uicfgpopuplbl, &ui_font_RobotoMono12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_uicfgpopuplbl, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_uicfgpopuplbl, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_uicfgpopuplbl, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_uicfgpopuplbl, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uicfgpopupbtnok = lv_button_create(ui_uicfgpopuppanel);
    lv_obj_set_height(ui_uicfgpopupbtnok, 34);
    lv_obj_set_width(ui_uicfgpopupbtnok, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_align(ui_uicfgpopupbtnok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uicfgpopupbtnok, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_uicfgpopupbtnok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uicfgpopupbtnok, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uicfgpopupbtnok, lv_color_hex(0x2BB3D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uicfgpopupbtnok, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uicfgpopupbtnok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_uicfgpopupbtnok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_uicfgpopupbtnok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_uicfgpopupbtnok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_uicfgpopupbtnok, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uicfgpopupbtnok, lv_color_hex(0x1A8FAB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_uicfgpopupbtnok, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_uicfgpopupbtnok);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "OK");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x062033), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnstart, ui_event_btnstart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uicfgpopupbtnok, ui_event_uicfgpopupbtnok, LV_EVENT_ALL, NULL);
    uic_lbltitle = ui_lbltitle;

}

void ui_scrconfig_screen_destroy(void)
{
    if(ui_scrconfig) lv_obj_del(ui_scrconfig);

    // NULL screen variables
    ui_scrconfig = NULL;
    ui_header = NULL;
    ui_hdrleft = NULL;
    ui_dot = NULL;
    uic_lbltitle = NULL;
    ui_lbltitle = NULL;
    ui_Label4 = NULL;
    ui_uikbdisplay = NULL;
    ui_rowscont = NULL;
    ui_row1 = NULL;
    ui_lblname1 = NULL;
    ui_lblvalue1 = NULL;
    ui_row2 = NULL;
    ui_lblname2 = NULL;
    ui_lblvalue2 = NULL;
    ui_row3 = NULL;
    ui_lblname3 = NULL;
    ui_lblvalue3 = NULL;
    ui_row4 = NULL;
    ui_lblname4 = NULL;
    ui_lblvalue4 = NULL;
    ui_btnstart = NULL;
    ui_Label7 = NULL;
    ui_Keyboard1 = NULL;
    ui_uicfgpopup = NULL;
    ui_uicfgpopuppanel = NULL;
    ui_uicfgpopuphdr = NULL;
    ui_uicfgpopupdot = NULL;
    ui_uicfgpopuptitle = NULL;
    ui_uicfgpopuplbl = NULL;
    ui_uicfgpopupbtnok = NULL;
    ui_Label5 = NULL;

}
