// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Powering_Up_screen_init();
    ui_Init_screen_init();
    ui_Running_screen_init();
    ui_Modo_screen_init();
    ui_Voltaje_screen_init();
    ui_Corriente_screen_init();
    ui_Resistencia_screen_init();
    ui_Voltaje_Limit_set_screen_init();
    ui_Corriente_Limit_set_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Powering_Up);
}

void ui_destroy(void)
{
    ui_Powering_Up_screen_destroy();
    ui_Init_screen_destroy();
    ui_Running_screen_destroy();
    ui_Modo_screen_destroy();
    ui_Voltaje_screen_destroy();
    ui_Corriente_screen_destroy();
    ui_Resistencia_screen_destroy();
    ui_Voltaje_Limit_set_screen_destroy();
    ui_Corriente_Limit_set_screen_destroy();
}
