// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_bar_corriente;
lv_obj_t * ui_Corriente = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_bar_corriente = NULL;
lv_obj_t * ui_voltaje_set1 = NULL;
lv_obj_t * ui_hora5 = NULL;
// event funtions

// build funtions

void ui_Corriente_screen_init(void)
{
    ui_Corriente = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Corriente, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Corriente);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -70);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SELECCIONE CORRIENTE DE OPERACION");

    ui_bar_corriente = lv_slider_create(ui_Corriente);
    lv_slider_set_value(ui_bar_corriente, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bar_corriente) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_bar_corriente, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_corriente, 150);
    lv_obj_set_height(ui_bar_corriente, 10);
    lv_obj_set_align(ui_bar_corriente, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bar_corriente, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bar_corriente,
                                                                                                    lv_obj_get_style_pad_right(ui_bar_corriente, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_voltaje_set1 = lv_label_create(ui_Corriente);
    lv_obj_set_width(ui_voltaje_set1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltaje_set1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltaje_set1, 0);
    lv_obj_set_y(ui_voltaje_set1, 50);
    lv_obj_set_align(ui_voltaje_set1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltaje_set1, "0.0000 A");

    ui_hora5 = ui_hora_create(ui_Corriente);
    lv_obj_set_x(ui_hora5, 98);
    lv_obj_set_y(ui_hora5, -109);

    uic_bar_corriente = ui_bar_corriente;

}

void ui_Corriente_screen_destroy(void)
{
    if(ui_Corriente) lv_obj_del(ui_Corriente);

    // NULL screen variables
    ui_Corriente = NULL;
    ui_Label3 = NULL;
    uic_bar_corriente = NULL;
    ui_bar_corriente = NULL;
    ui_voltaje_set1 = NULL;
    ui_hora5 = NULL;

}
