// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

// COMPONENT hora

lv_obj_t * ui_hora_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_hora;
    cui_hora = lv_label_create(comp_parent);
    lv_obj_set_width(cui_hora, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_hora, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_hora, 98);
    lv_obj_set_y(cui_hora, -109);
    lv_obj_set_align(cui_hora, LV_ALIGN_CENTER);
    lv_label_set_text(cui_hora, "2026/06/26 21:45");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_HORA_NUM);
    children[UI_COMP_HORA_HORA] = cui_hora;
    lv_obj_add_event_cb(cui_hora, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_hora, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_hora_create_hook(cui_hora);
    return cui_hora;
}

