// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_corr_limit_set;
lv_obj_t * uic_bar_corr_limit;
lv_obj_t * uic_Corriente_Limit_set;
lv_obj_t * ui_Corriente_Limit_set = NULL;
lv_obj_t * ui_Corriente_limite = NULL;
lv_obj_t * ui_bar_corr_limit = NULL;
lv_obj_t * ui_corr_limit_set = NULL;
lv_obj_t * ui_hora7 = NULL;
// event funtions

// build funtions

void ui_Corriente_Limit_set_screen_init(void)
{
    ui_Corriente_Limit_set = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Corriente_Limit_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Corriente_limite = lv_label_create(ui_Corriente_Limit_set);
    lv_obj_set_width(ui_Corriente_limite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Corriente_limite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Corriente_limite, 0);
    lv_obj_set_y(ui_Corriente_limite, -70);
    lv_obj_set_align(ui_Corriente_limite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Corriente_limite, "SELECCIONE CORRIENTE MAXIMA");

    ui_bar_corr_limit = lv_slider_create(ui_Corriente_Limit_set);
    lv_slider_set_value(ui_bar_corr_limit, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bar_corr_limit) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_bar_corr_limit, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_corr_limit, 150);
    lv_obj_set_height(ui_bar_corr_limit, 10);
    lv_obj_set_align(ui_bar_corr_limit, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bar_corr_limit, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bar_corr_limit,
                                                                                                     lv_obj_get_style_pad_right(ui_bar_corr_limit, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_corr_limit_set = lv_label_create(ui_Corriente_Limit_set);
    lv_obj_set_width(ui_corr_limit_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_corr_limit_set, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_corr_limit_set, 0);
    lv_obj_set_y(ui_corr_limit_set, 50);
    lv_obj_set_align(ui_corr_limit_set, LV_ALIGN_CENTER);
    lv_label_set_text(ui_corr_limit_set, "0.0000 A");

    ui_hora7 = ui_hora_create(ui_Corriente_Limit_set);
    lv_obj_set_x(ui_hora7, 98);
    lv_obj_set_y(ui_hora7, -109);

    uic_Corriente_Limit_set = ui_Corriente_Limit_set;
    uic_bar_corr_limit = ui_bar_corr_limit;
    uic_corr_limit_set = ui_corr_limit_set;

}

void ui_Corriente_Limit_set_screen_destroy(void)
{
    if(ui_Corriente_Limit_set) lv_obj_del(ui_Corriente_Limit_set);

    // NULL screen variables
    uic_Corriente_Limit_set = NULL;
    ui_Corriente_Limit_set = NULL;
    ui_Corriente_limite = NULL;
    uic_bar_corr_limit = NULL;
    ui_bar_corr_limit = NULL;
    uic_corr_limit_set = NULL;
    ui_corr_limit_set = NULL;
    ui_hora7 = NULL;

}
