// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

void ui_comp_Hora_create_hook(lv_obj_t * comp)
{
}

void ui_comp_hora_create_hook(lv_obj_t * comp)
{
}
