// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_CORRIENTE_H
#define UI_CORRIENTE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Corriente
extern void ui_Corriente_screen_init(void);
extern void ui_Corriente_screen_destroy(void);
extern lv_obj_t * ui_Corriente;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_bar_corriente;
extern lv_obj_t * ui_voltaje_set1;
extern lv_obj_t * ui_hora5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_bar_corriente;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

