// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef _UI_COMP_HORA_H
#define _UI_COMP_HORA_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT hora
#define UI_COMP_HORA_HORA 0
#define _UI_COMP_HORA_NUM 1
lv_obj_t * ui_hora_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
