// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_CORRIENTE_LIMIT_SET_H
#define UI_CORRIENTE_LIMIT_SET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Corriente_Limit_set
extern void ui_Corriente_Limit_set_screen_init(void);
extern void ui_Corriente_Limit_set_screen_destroy(void);
extern lv_obj_t * ui_Corriente_Limit_set;
extern lv_obj_t * ui_Corriente_limite;
extern lv_obj_t * ui_bar_corr_limit;
extern lv_obj_t * ui_corr_limit_set;
extern lv_obj_t * ui_hora7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Corriente_Limit_set;
extern lv_obj_t * uic_bar_corr_limit;
extern lv_obj_t * uic_corr_limit_set;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

