// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

void Seleccionarmodo(lv_event_t * e)
{
	// Your code here
}

void Avanzaropcion(lv_event_t * e)
{
	// Your code here
}
