// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_INIT_H
#define UI_INIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Init
extern void ui_Init_screen_init(void);
extern void ui_Init_screen_destroy(void);
extern lv_obj_t * ui_Init;
extern lv_obj_t * ui_inicio_de_programa;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_hora1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_INICIO;
extern lv_obj_t * uic_inicio_de_programa;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

