// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_inicio_de_programa;
lv_obj_t * uic_INICIO;
lv_obj_t * ui_Init = NULL;
lv_obj_t * ui_inicio_de_programa = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_hora1 = NULL;
// event funtions

// build funtions

void ui_Init_screen_init(void)
{
    ui_Init = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Init, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_inicio_de_programa = lv_roller_create(ui_Init);
    lv_roller_set_options(ui_inicio_de_programa, "INICIAR\nCONFIGURAR\nALARMAS", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_inicio_de_programa, 37);
    lv_obj_set_width(ui_inicio_de_programa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_inicio_de_programa, 0);
    lv_obj_set_y(ui_inicio_de_programa, 20);
    lv_obj_set_align(ui_inicio_de_programa, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_Init);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -70);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SELECCIONE ACCION");

    ui_hora1 = ui_hora_create(ui_Init);
    lv_obj_set_x(ui_hora1, 98);
    lv_obj_set_y(ui_hora1, -109);

    uic_INICIO = ui_Init;
    uic_inicio_de_programa = ui_inicio_de_programa;

}

void ui_Init_screen_destroy(void)
{
    if(ui_Init) lv_obj_del(ui_Init);

    // NULL screen variables
    uic_INICIO = NULL;
    ui_Init = NULL;
    uic_inicio_de_programa = NULL;
    ui_inicio_de_programa = NULL;
    ui_Label5 = NULL;
    ui_hora1 = NULL;

}
