// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_Modo_seleccionado;
lv_obj_t * uic_Modo;
lv_obj_t * ui_Modo = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Modo_seleccionado = NULL;
lv_obj_t * ui_hora4 = NULL;
// event funtions
void ui_event_Modo_seleccionado(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Seleccionarmodo(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Avanzaropcion(e);
    }
}

// build funtions

void ui_Modo_screen_init(void)
{
    ui_Modo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Modo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Modo);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -70);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SELECCIONE MODO DE OPERACION");

    ui_Modo_seleccionado = lv_roller_create(ui_Modo);
    lv_roller_set_options(ui_Modo_seleccionado, "CR\nCV\nCC", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Modo_seleccionado, 100);
    lv_obj_set_width(ui_Modo_seleccionado, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Modo_seleccionado, 0);
    lv_obj_set_y(ui_Modo_seleccionado, 20);
    lv_obj_set_align(ui_Modo_seleccionado, LV_ALIGN_CENTER);

    ui_hora4 = ui_hora_create(ui_Modo);
    lv_obj_set_x(ui_hora4, 98);
    lv_obj_set_y(ui_hora4, -109);

    lv_obj_add_event_cb(ui_Modo_seleccionado, ui_event_Modo_seleccionado, LV_EVENT_ALL, NULL);
    uic_Modo = ui_Modo;
    uic_Modo_seleccionado = ui_Modo_seleccionado;

}

void ui_Modo_screen_destroy(void)
{
    if(ui_Modo) lv_obj_del(ui_Modo);

    // NULL screen variables
    uic_Modo = NULL;
    ui_Modo = NULL;
    ui_Label6 = NULL;
    uic_Modo_seleccionado = NULL;
    ui_Modo_seleccionado = NULL;
    ui_hora4 = NULL;

}
