// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_MODO_H
#define UI_MODO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Modo
extern void ui_Modo_screen_init(void);
extern void ui_Modo_screen_destroy(void);
extern lv_obj_t * ui_Modo;
extern lv_obj_t * ui_Label6;
extern void ui_event_Modo_seleccionado(lv_event_t * e);
extern lv_obj_t * ui_Modo_seleccionado;
extern lv_obj_t * ui_hora4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Modo;
extern lv_obj_t * uic_Modo_seleccionado;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

