// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_barra_de_carga;
lv_obj_t * ui_Powering_Up = NULL;
lv_obj_t * ui_barra_de_carga = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_hora = NULL;
// event funtions

// build funtions

void ui_Powering_Up_screen_init(void)
{
    ui_Powering_Up = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Powering_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_barra_de_carga = lv_bar_create(ui_Powering_Up);
    lv_obj_set_width(ui_barra_de_carga, 150);
    lv_obj_set_height(ui_barra_de_carga, 10);
    lv_obj_set_align(ui_barra_de_carga, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barra_de_carga, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barra_de_carga,
                                                                                                     lv_obj_get_style_pad_right(ui_barra_de_carga, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label1 = lv_label_create(ui_Powering_Up);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 43);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "INICIANDO");

    ui_hora = ui_hora_create(ui_Powering_Up);
    lv_obj_set_x(ui_hora, 98);
    lv_obj_set_y(ui_hora, -109);

    uic_barra_de_carga = ui_barra_de_carga;

}

void ui_Powering_Up_screen_destroy(void)
{
    if(ui_Powering_Up) lv_obj_del(ui_Powering_Up);

    // NULL screen variables
    ui_Powering_Up = NULL;
    uic_barra_de_carga = NULL;
    ui_barra_de_carga = NULL;
    ui_Label1 = NULL;
    ui_hora = NULL;

}
