// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_POWERING_UP_H
#define UI_POWERING_UP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Powering_Up
extern void ui_Powering_Up_screen_init(void);
extern void ui_Powering_Up_screen_destroy(void);
extern lv_obj_t * ui_Powering_Up;
extern lv_obj_t * ui_barra_de_carga;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_hora;
// CUSTOM VARIABLES
extern lv_obj_t * uic_barra_de_carga;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

