// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_Led_Corriente;
lv_obj_t * uic_Led_Voltaje;
lv_obj_t * uic_modo_actual;
lv_obj_t * uic_potencia_actual;
lv_obj_t * uic_corriente_actual;
lv_obj_t * uic_voltaje_actual;
lv_obj_t * uic_RUNNING;
lv_obj_t * ui_Running = NULL;
lv_obj_t * ui_voltaje_actual = NULL;
lv_obj_t * ui_corriente_actual = NULL;
lv_obj_t * ui_potencia_actual = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_modo_actual = NULL;
lv_obj_t * ui_Led_Voltaje = NULL;
lv_obj_t * ui_Vol = NULL;
lv_obj_t * ui_Led_Corriente = NULL;
lv_obj_t * ui_Cor = NULL;
lv_obj_t * ui_hora2 = NULL;
// event funtions

// build funtions

void ui_Running_screen_init(void)
{
    ui_Running = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Running, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltaje_actual = lv_label_create(ui_Running);
    lv_obj_set_width(ui_voltaje_actual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltaje_actual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltaje_actual, -60);
    lv_obj_set_y(ui_voltaje_actual, -70);
    lv_obj_set_align(ui_voltaje_actual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltaje_actual, "00.000 V");
    lv_obj_set_style_text_font(ui_voltaje_actual, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_corriente_actual = lv_label_create(ui_Running);
    lv_obj_set_width(ui_corriente_actual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_corriente_actual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_corriente_actual, -60);
    lv_obj_set_y(ui_corriente_actual, 0);
    lv_obj_set_align(ui_corriente_actual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_corriente_actual, "0.0000 A");
    lv_obj_set_style_text_font(ui_corriente_actual, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_potencia_actual = lv_label_create(ui_Running);
    lv_obj_set_width(ui_potencia_actual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_potencia_actual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_potencia_actual, -60);
    lv_obj_set_y(ui_potencia_actual, 70);
    lv_obj_set_align(ui_potencia_actual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_potencia_actual, "00.00 W");
    lv_obj_set_style_text_font(ui_potencia_actual, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Running);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 105);
    lv_obj_set_y(ui_Label8, 35);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "MODO");

    ui_modo_actual = lv_label_create(ui_Running);
    lv_obj_set_width(ui_modo_actual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_modo_actual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_modo_actual, 105);
    lv_obj_set_y(ui_modo_actual, 75);
    lv_obj_set_align(ui_modo_actual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_modo_actual, "");
    lv_obj_set_style_text_font(ui_modo_actual, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Led_Voltaje = lv_obj_create(ui_Running);
    lv_obj_set_width(ui_Led_Voltaje, 20);
    lv_obj_set_height(ui_Led_Voltaje, 20);
    lv_obj_set_x(ui_Led_Voltaje, 120);
    lv_obj_set_y(ui_Led_Voltaje, -70);
    lv_obj_set_align(ui_Led_Voltaje, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Led_Voltaje, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Led_Voltaje, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Led_Voltaje, lv_color_hex(0xABABAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Led_Voltaje, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vol = lv_label_create(ui_Running);
    lv_obj_set_width(ui_Vol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Vol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Vol, 140);
    lv_obj_set_y(ui_Vol, -70);
    lv_obj_set_align(ui_Vol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Vol, "V");

    ui_Led_Corriente = lv_obj_create(ui_Running);
    lv_obj_set_width(ui_Led_Corriente, 20);
    lv_obj_set_height(ui_Led_Corriente, 20);
    lv_obj_set_x(ui_Led_Corriente, 120);
    lv_obj_set_y(ui_Led_Corriente, -30);
    lv_obj_set_align(ui_Led_Corriente, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Led_Corriente, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Led_Corriente, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Led_Corriente, lv_color_hex(0xAABBAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Led_Corriente, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cor = lv_label_create(ui_Running);
    lv_obj_set_width(ui_Cor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cor, 140);
    lv_obj_set_y(ui_Cor, -30);
    lv_obj_set_align(ui_Cor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Cor, "C");

    ui_hora2 = ui_hora_create(ui_Running);
    lv_obj_set_x(ui_hora2, 98);
    lv_obj_set_y(ui_hora2, -109);

    uic_RUNNING = ui_Running;
    uic_voltaje_actual = ui_voltaje_actual;
    uic_corriente_actual = ui_corriente_actual;
    uic_potencia_actual = ui_potencia_actual;
    uic_modo_actual = ui_modo_actual;
    uic_Led_Voltaje = ui_Led_Voltaje;
    uic_Led_Corriente = ui_Led_Corriente;

}

void ui_Running_screen_destroy(void)
{
    if(ui_Running) lv_obj_del(ui_Running);

    // NULL screen variables
    uic_RUNNING = NULL;
    ui_Running = NULL;
    uic_voltaje_actual = NULL;
    ui_voltaje_actual = NULL;
    uic_corriente_actual = NULL;
    ui_corriente_actual = NULL;
    uic_potencia_actual = NULL;
    ui_potencia_actual = NULL;
    ui_Label8 = NULL;
    uic_modo_actual = NULL;
    ui_modo_actual = NULL;
    uic_Led_Voltaje = NULL;
    ui_Led_Voltaje = NULL;
    ui_Vol = NULL;
    uic_Led_Corriente = NULL;
    ui_Led_Corriente = NULL;
    ui_Cor = NULL;
    ui_hora2 = NULL;

}
