// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_RUNNING_H
#define UI_RUNNING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Running
extern void ui_Running_screen_init(void);
extern void ui_Running_screen_destroy(void);
extern lv_obj_t * ui_Running;
extern lv_obj_t * ui_voltaje_actual;
extern lv_obj_t * ui_corriente_actual;
extern lv_obj_t * ui_potencia_actual;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_modo_actual;
extern lv_obj_t * ui_Led_Voltaje;
extern lv_obj_t * ui_Vol;
extern lv_obj_t * ui_Led_Corriente;
extern lv_obj_t * ui_Cor;
extern lv_obj_t * ui_hora2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RUNNING;
extern lv_obj_t * uic_voltaje_actual;
extern lv_obj_t * uic_corriente_actual;
extern lv_obj_t * uic_potencia_actual;
extern lv_obj_t * uic_modo_actual;
extern lv_obj_t * uic_Led_Voltaje;
extern lv_obj_t * uic_Led_Corriente;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

