// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_Resistencia_set;
lv_obj_t * uic_bar_resistencia;
lv_obj_t * ui_Resistencia = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_bar_resistencia = NULL;
lv_obj_t * ui_Resistencia_set = NULL;
lv_obj_t * ui_hora6 = NULL;
// event funtions

// build funtions

void ui_Resistencia_screen_init(void)
{
    ui_Resistencia = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Resistencia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Resistencia);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -70);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SELECCIONE RESISTENCIA DE OPERACION");

    ui_bar_resistencia = lv_slider_create(ui_Resistencia);
    lv_slider_set_value(ui_bar_resistencia, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bar_resistencia) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_bar_resistencia, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_resistencia, 150);
    lv_obj_set_height(ui_bar_resistencia, 10);
    lv_obj_set_align(ui_bar_resistencia, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bar_resistencia, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bar_resistencia,
                                                                                                      lv_obj_get_style_pad_right(ui_bar_resistencia, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Resistencia_set = lv_label_create(ui_Resistencia);
    lv_obj_set_width(ui_Resistencia_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Resistencia_set, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Resistencia_set, 0);
    lv_obj_set_y(ui_Resistencia_set, 50);
    lv_obj_set_align(ui_Resistencia_set, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Resistencia_set, "0000 Ohm");

    ui_hora6 = ui_hora_create(ui_Resistencia);
    lv_obj_set_x(ui_hora6, 98);
    lv_obj_set_y(ui_hora6, -109);

    uic_bar_resistencia = ui_bar_resistencia;
    uic_Resistencia_set = ui_Resistencia_set;

}

void ui_Resistencia_screen_destroy(void)
{
    if(ui_Resistencia) lv_obj_del(ui_Resistencia);

    // NULL screen variables
    ui_Resistencia = NULL;
    ui_Label4 = NULL;
    uic_bar_resistencia = NULL;
    ui_bar_resistencia = NULL;
    uic_Resistencia_set = NULL;
    ui_Resistencia_set = NULL;
    ui_hora6 = NULL;

}
