// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_RESISTENCIA_H
#define UI_RESISTENCIA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Resistencia
extern void ui_Resistencia_screen_init(void);
extern void ui_Resistencia_screen_destroy(void);
extern lv_obj_t * ui_Resistencia;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_bar_resistencia;
extern lv_obj_t * ui_Resistencia_set;
extern lv_obj_t * ui_hora6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_bar_resistencia;
extern lv_obj_t * uic_Resistencia_set;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

