// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_VOLTAJE_H
#define UI_VOLTAJE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Voltaje
extern void ui_Voltaje_screen_init(void);
extern void ui_Voltaje_screen_destroy(void);
extern lv_obj_t * ui_Voltaje;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_bar_voltaje;
extern lv_obj_t * ui_voltaje_set;
extern lv_obj_t * ui_hora3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_bar_voltaje;
extern lv_obj_t * uic_voltaje_set;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

