// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_voltaje_lim_set;
lv_obj_t * uic_bar_voltaje_limit_set;
lv_obj_t * uic_Voltaje_limite;
lv_obj_t * ui_Voltaje_Limit_set = NULL;
lv_obj_t * ui_Voltaje_limite = NULL;
lv_obj_t * ui_bar_voltaje_limit_set = NULL;
lv_obj_t * ui_voltaje_lim_set = NULL;
lv_obj_t * ui_hora8 = NULL;
// event funtions

// build funtions

void ui_Voltaje_Limit_set_screen_init(void)
{
    ui_Voltaje_Limit_set = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Voltaje_Limit_set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Voltaje_limite = lv_label_create(ui_Voltaje_Limit_set);
    lv_obj_set_width(ui_Voltaje_limite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Voltaje_limite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Voltaje_limite, 0);
    lv_obj_set_y(ui_Voltaje_limite, -70);
    lv_obj_set_align(ui_Voltaje_limite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Voltaje_limite, "SELECCIONE VOLTAJE MAXIMO");

    ui_bar_voltaje_limit_set = lv_slider_create(ui_Voltaje_Limit_set);
    lv_slider_set_value(ui_bar_voltaje_limit_set, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bar_voltaje_limit_set) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(
            ui_bar_voltaje_limit_set, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_voltaje_limit_set, 150);
    lv_obj_set_height(ui_bar_voltaje_limit_set, 10);
    lv_obj_set_align(ui_bar_voltaje_limit_set, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bar_voltaje_limit_set,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bar_voltaje_limit_set,
                                                                                  lv_obj_get_style_pad_right(ui_bar_voltaje_limit_set, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_voltaje_lim_set = lv_label_create(ui_Voltaje_Limit_set);
    lv_obj_set_width(ui_voltaje_lim_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltaje_lim_set, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltaje_lim_set, 0);
    lv_obj_set_y(ui_voltaje_lim_set, 50);
    lv_obj_set_align(ui_voltaje_lim_set, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltaje_lim_set, "00.000 V");

    ui_hora8 = ui_hora_create(ui_Voltaje_Limit_set);
    lv_obj_set_x(ui_hora8, 98);
    lv_obj_set_y(ui_hora8, -109);

    uic_Voltaje_limite = ui_Voltaje_limite;
    uic_bar_voltaje_limit_set = ui_bar_voltaje_limit_set;
    uic_voltaje_lim_set = ui_voltaje_lim_set;

}

void ui_Voltaje_Limit_set_screen_destroy(void)
{
    if(ui_Voltaje_Limit_set) lv_obj_del(ui_Voltaje_Limit_set);

    // NULL screen variables
    ui_Voltaje_Limit_set = NULL;
    uic_Voltaje_limite = NULL;
    ui_Voltaje_limite = NULL;
    uic_bar_voltaje_limit_set = NULL;
    ui_bar_voltaje_limit_set = NULL;
    uic_voltaje_lim_set = NULL;
    ui_voltaje_lim_set = NULL;
    ui_hora8 = NULL;

}
