// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#include "ui.h"

lv_obj_t * uic_voltaje_set;
lv_obj_t * uic_bar_voltaje;
lv_obj_t * ui_Voltaje = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_bar_voltaje = NULL;
lv_obj_t * ui_voltaje_set = NULL;
lv_obj_t * ui_hora3 = NULL;
// event funtions

// build funtions

void ui_Voltaje_screen_init(void)
{
    ui_Voltaje = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Voltaje, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Voltaje);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -70);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SELECCIONE VOLTAJE DE OPERACION");

    ui_bar_voltaje = lv_slider_create(ui_Voltaje);
    lv_slider_set_value(ui_bar_voltaje, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_bar_voltaje) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_bar_voltaje, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_voltaje, 150);
    lv_obj_set_height(ui_bar_voltaje, 10);
    lv_obj_set_align(ui_bar_voltaje, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_bar_voltaje, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_bar_voltaje,
                                                                                                  lv_obj_get_style_pad_right(ui_bar_voltaje, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_voltaje_set = lv_label_create(ui_Voltaje);
    lv_obj_set_width(ui_voltaje_set, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltaje_set, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltaje_set, 0);
    lv_obj_set_y(ui_voltaje_set, 50);
    lv_obj_set_align(ui_voltaje_set, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltaje_set, "00.000 V");

    ui_hora3 = ui_hora_create(ui_Voltaje);
    lv_obj_set_x(ui_hora3, 98);
    lv_obj_set_y(ui_hora3, -109);

    uic_bar_voltaje = ui_bar_voltaje;
    uic_voltaje_set = ui_voltaje_set;

}

void ui_Voltaje_screen_destroy(void)
{
    if(ui_Voltaje) lv_obj_del(ui_Voltaje);

    // NULL screen variables
    ui_Voltaje = NULL;
    ui_Label2 = NULL;
    uic_bar_voltaje = NULL;
    ui_bar_voltaje = NULL;
    uic_voltaje_set = NULL;
    ui_voltaje_set = NULL;
    ui_hora3 = NULL;

}
