// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: Carga Electronica

#ifndef UI_VOLTAJE_LIMIT_SET_H
#define UI_VOLTAJE_LIMIT_SET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Voltaje_Limit_set
extern void ui_Voltaje_Limit_set_screen_init(void);
extern void ui_Voltaje_Limit_set_screen_destroy(void);
extern lv_obj_t * ui_Voltaje_Limit_set;
extern lv_obj_t * ui_Voltaje_limite;
extern lv_obj_t * ui_bar_voltaje_limit_set;
extern lv_obj_t * ui_voltaje_lim_set;
extern lv_obj_t * ui_hora8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Voltaje_limite;
extern lv_obj_t * uic_bar_voltaje_limit_set;
extern lv_obj_t * uic_voltaje_lim_set;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

