// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Spinbox1 = NULL;lv_obj_t *ui_Spinbox2 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Label10 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinbox1 = lv_spinbox_create(ui_Screen1);
lv_obj_set_width( ui_Spinbox1, 166);
lv_obj_set_height( ui_Spinbox1, 65);
lv_obj_set_x( ui_Spinbox1, -30 );
lv_obj_set_y( ui_Spinbox1, -45 );
lv_obj_set_align( ui_Spinbox1, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_Spinbox1, 5, 2);
lv_spinbox_set_range( ui_Spinbox1, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

ui_Spinbox2 = lv_spinbox_create(ui_Screen1);
lv_obj_set_width( ui_Spinbox2, 164);
lv_obj_set_height( ui_Spinbox2, 66);
lv_obj_set_x( ui_Spinbox2, -31 );
lv_obj_set_y( ui_Spinbox2, 40 );
lv_obj_set_align( ui_Spinbox2, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_Spinbox2, 5, 2);
lv_spinbox_set_range( ui_Spinbox2, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox2, 1 - 1);

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 91 );
lv_obj_set_y( ui_Label8, -43 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"text");

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 92 );
lv_obj_set_y( ui_Label9, 41 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"text");

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -3 );
lv_obj_set_y( ui_Label10, -100 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"text");

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Spinbox1= NULL;
ui_Spinbox2= NULL;
ui_Label8= NULL;
ui_Label9= NULL;
ui_Label10= NULL;

}
