// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#ifndef _FREQ_RESPONSE_ANALYZER_UI_H
#define _FREQ_RESPONSE_ANALYZER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_scrconfig.h"
#include "screens/ui_scrsweep.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * cursorblink_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * animindicatorpulse_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_RobotoMono12);
LV_FONT_DECLARE(ui_font_RobotoMono14);
LV_FONT_DECLARE(ui_font_RobotoMono18);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
