// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_btn_start(lv_event_t * e);
void ui_event_cfg_popup_ok(lv_event_t * e);
void ui_event_btn_pausar(lv_event_t * e);
void ui_event_btn_config(lv_event_t * e);
void ui_event_btn_reiniciar(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
