// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#include "ui.h"
#include "esp_log.h"
#include "app_common.h"

void ui_event_btn_start(lv_event_t * e)
{
    menu_event_msg_t ev = {
        .type = MENU_EVT_SWEEP_START,
    };
    if (xQueueSend(queue_menu_events, &ev, 0) != pdTRUE)
    {
        ESP_LOGW("UI", "queue_menu_events llena, pedido de inicio descartado");
    }
}

void ui_event_btn_pausar(lv_event_t * e)
{
	ESP_LOGI("UI", "Barrido pausado");
}

void ui_event_btn_config(lv_event_t * e)
{
    lv_disp_load_scr(ui_scrconfig);
    ESP_LOGI("UI", "Volviendo a config");
}

void ui_event_btn_reiniciar(lv_event_t * e)
{
	ESP_LOGI("UI", "Reiniciando barrido");
}

void ui_event_cfg_popup_ok(lv_event_t * e)
{
    lv_obj_add_flag(ui_uicfgpopup, LV_OBJ_FLAG_HIDDEN);
}
