// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_btn_test_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
