// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: freq_response_analyzer

#include "ui.h"

void on_btn_test_clicked(lv_event_t * e)
{
	// Your code here
}
